In [2]:
import numpy as np

In [4]:
# creating numpy arrays

data = np.array([[1, 2, 3], [4, 5, 6]])
print(data.shape, data.dtype)

(2, 3) int64


In [9]:
# converting dtype float64 to dtype int will truncates values

arr = np.array([1.2, -0.5, 8.3, -9.9])
print(arr.dtype)

arr.astype(np.int32)

float64


array([ 1,  0,  8, -9], dtype=int32)

In [10]:
# vectorization - apply batch operations without for loops

arr = np.ones(4)
print(arr)

arr * 3

[1. 1. 1. 1.]


array([3., 3., 3., 3.])

In [11]:
# comparisons between two array result in a array of bools

arr1 = np.ones(4)
arr2 = np.zeros(4)

arr1 > arr2

array([ True,  True,  True,  True])

In [13]:
# array slices are views on the original array

arr1 = np.ones(5)

arr_slice = arr1[2:4]
print(arr_slice)

arr_slice[0] = 0 # this will change both arr_slice

print(arr_slice, arr1)

[1. 1.]
[0. 1.] [1. 1. 0. 1. 1.]


In [1]:
# bare slice will assign to all values

arr = np.ones(4)
print(arr)
arr[:] = 0
print(arr)

NameError: name 'np' is not defined

In [17]:
# elements can be accessed recursively or with a comma-seperated list

arr = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

print(arr[1][2])
print(arr[1, 2])

2
2


In [19]:
# passing multiple slices

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[:1, 1:]

array([[2, 3]])

In [20]:
# searching for a specific value in arrays

animals = np.array(["cat", "cat", "dog", "dog", "dog", "cat"])

animals == "cat"

array([ True,  True, False, False, False,  True])

In [24]:
# passing boolean arrays as indices

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(animals == "cat")
print(arr[animals == "cat"])

[ True  True False False False  True]
[[ 1  2]
 [ 3  4]
 [11 12]]


In [34]:
# negation with ~

dogs = ~(animals == "cat")
cats = ~(dogs)

print(cats)

[ True  True False False False  True]


In [35]:
# indexing with multiple bool conditions

all_animals = (animals == "cat") | (animals == "dog")
all_animals

array([ True,  True,  True,  True,  True,  True])

In [17]:
# fancy indexing - indexing using arrays

arr = np.arange(16).reshape(4, 4)

print(arr[[1, 3]]) # outputs multiple values (grouped into one) (think as if two indexing operations)
print(arr[[-1, -3]]) # fancy indexing with negative indices

[[ 4  5  6  7]
 [12 13 14 15]]
[[12 13 14 15]
 [ 4  5  6  7]]


In [10]:
# indexing with two array

print(f"{arr}\n")

print(arr[[3, 0, 2, 1], [3, 1, 0, 2]]) # considers the index a set of coordinates

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[16  2  9  7]


In [18]:
# transposing arrays

arr = np.arange(8).reshape(2, 4)

print(f"{arr}\n")
print(arr.T)

[[0 1 2 3]
 [4 5 6 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [23]:
# matrix product

arr = np.arange(8).reshape(4, 2)

prod = np.dot(arr.T, arr)
prod2 = arr.T @ arr # using infix operator

print(prod2)
print(prod)

[[56 68]
 [68 84]]
[[56 68]
 [68 84]]


In [28]:
# swapping axes

arr = np.arange(8).reshape(2, 4)
print(arr, arr.shape)

arr.swapaxes(0, 1)

[[0 1 2 3]
 [4 5 6 7]] (2, 4)


array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [29]:
# time an action

%timeit np.random.standard_normal(300)

9.77 µs ± 23 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [31]:
# creating your own random number generator

bot = np.random.default_rng(seed=1000)
data = bot.standard_normal((2, 3))
data

array([[-0.32133021, -0.48566148,  1.68005813],
       [ 1.97052688,  0.15518366, -1.25776545]])

In [93]:
# fine tuning random number generation with generator object

bot = np.random.default_rng(seed=100) # generator allows you to set the seed for reproducability

more = bot.integers((2, 3))
more

array([1, 2])

In [3]:
# ufuncs - functions that perform element-wise operations on ndarrays

arr = np.arange(5)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [12]:
arr = np.arange(3)

# unary ufuncs 
print(np.sqrt(arr))

# binary ufuncs
arr2 = np.arange(3)
print(np.add(arr, arr2))

# optional out argument
out = np.ones_like(arr, dtype="float64")
np.exp(arr, out=out)
print(out)

[0.         1.         1.41421356]
[0 2 4]
[1.         2.71828183 7.3890561 ]


In [14]:
arr = np.arange(-5, 5, 0.01)


AttributeError: 'numpy.ndarray' object has no attribute 'count'